<?php

use App\Http\Controllers\Api\LocationController;
use App\Http\Controllers\Api\MobileSyncController;
use App\Http\Controllers\Api\NotificationsController;
use App\Http\Controllers\Api\PersonnelController;
use App\Http\Controllers\Api\ProfileController;
use App\Http\Controllers\Api\WorkOrderAssessmentController;
use App\Http\Controllers\Api\WorkOrderAssignmentController;
use App\Http\Controllers\Api\WorkOrderCategoryController;
use App\Http\Controllers\Api\WorkOrderController;
use App\Http\Controllers\Api\WorkOrderExecutionController;
use App\Http\Controllers\Api\WorkOrderWorkflowController;
use App\Http\Controllers\Auth\ApiAuthController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function (): void {
    Route::get('/health', static fn (): array => ['status' => 'ok']);
    Route::post('/auth/login', [ApiAuthController::class, 'login'])->middleware('throttle:5,1');
    Route::middleware(['auth:sanctum', 'api.token', 'approved'])->group(function (): void {
        Route::get('/me', [ApiAuthController::class, 'me']);
        Route::get('/notifications', [NotificationsController::class, 'index']);
        Route::post('/notifications/read-all', [NotificationsController::class, 'readAll']);
        Route::post('/notifications/{notification}/read', [NotificationsController::class, 'read']);
        Route::post('/auth/logout', [ApiAuthController::class, 'logout']);
        Route::get('/me/profile', [ProfileController::class, 'show']);
        Route::get('/me/active-work-session', [WorkOrderExecutionController::class, 'active']);
        Route::get('/mobile/bootstrap', [MobileSyncController::class, 'bootstrap']);
        Route::post('/mobile/operations', [MobileSyncController::class, 'operation']);
        Route::post('/mobile/media', [MobileSyncController::class, 'media']);
        Route::patch('/me/profile', [ProfileController::class, 'update']);
        Route::get('/personnel', [PersonnelController::class, 'index']);
        Route::get('/personnel/{personnel}', [PersonnelController::class, 'show']);
        Route::get('/skills', [PersonnelController::class, 'skills']);
        Route::get('/campuses', [LocationController::class, 'campuses']);
        Route::get('/buildings', [LocationController::class, 'buildings']);
        Route::get('/locations', [LocationController::class, 'locations']);
        Route::get('/work-orders', [WorkOrderController::class, 'index']);
        Route::get('/work-orders/assigned', [WorkOrderController::class, 'assigned']);
        Route::get('/work-order-categories', [WorkOrderCategoryController::class, 'index']);
        Route::post('/work-orders', [WorkOrderController::class, 'store']);
        Route::post('/work-orders/direct', [WorkOrderController::class, 'storeDirect']);
        Route::post('/work-orders/{workOrder}/workflow/{action}', [WorkOrderWorkflowController::class, 'action']);
        Route::post('/work-orders/{workOrder}/assignments', [WorkOrderAssignmentController::class, 'store']);
        Route::delete('/work-orders/{workOrder}/assignments/{assignment}', [WorkOrderAssignmentController::class, 'destroy']);
        Route::get('/work-orders/{workOrder}/assessments', [WorkOrderAssessmentController::class, 'index']);
        Route::post('/work-orders/{workOrder}/assessment/acknowledge', [WorkOrderAssessmentController::class, 'acknowledge']);
        Route::post('/work-orders/{workOrder}/assessments', [WorkOrderAssessmentController::class, 'store']);
        Route::post('/work-orders/{workOrder}/assessment/resolve/{decision}', [WorkOrderAssessmentController::class, 'resolve']);
        Route::get('/work-orders/{workOrder}/sessions', [WorkOrderExecutionController::class, 'sessions']);
        Route::post('/work-orders/{workOrder}/start-work', [WorkOrderExecutionController::class, 'start']);
        Route::post('/work-orders/{workOrder}/sessions/{session}/updates', [WorkOrderExecutionController::class, 'update']);
        Route::post('/work-orders/{workOrder}/sessions/{session}/end', [WorkOrderExecutionController::class, 'end']);
        Route::post('/work-orders/{workOrder}/sessions/{session}/force-end', [WorkOrderExecutionController::class, 'forceEnd']);
        Route::post('/work-orders/{workOrder}/submit-for-verification', [WorkOrderExecutionController::class, 'submit']);
        Route::post('/work-orders/{workOrder}/verify', [WorkOrderExecutionController::class, 'verify']);
        Route::post('/work-orders/{workOrder}/return-for-work', [WorkOrderExecutionController::class, 'returnForWork']);
        Route::post('/work-orders/{workOrder}/release-investigation', [WorkOrderExecutionController::class, 'releaseInvestigation']);
        Route::get('/work-orders/{workOrder}', [WorkOrderController::class, 'show']);
        Route::patch('/work-orders/{workOrder}', [WorkOrderController::class, 'update']);
        Route::get('/work-orders/{workOrder}/attachments/{attachment}', [WorkOrderController::class, 'attachment']);
    });
});
