@extends('layouts.app')
@section('title', isset($order) ? 'Update Work Order' : 'New Work Order Request')
@section('content')
<x-page-header :title="isset($order) ? 'Update '.$order->work_order_number : 'New Work Order Request'" description="Tell us what needs attention and where it is located. Fields marked with * are required." />
@if(isset($order) && $order->status === \App\Enums\WorkOrderStatus::NeedsInformation)<div class="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><p class="font-semibold">FMO requested additional information</p><p class="mt-1">Please update the request and include your response before resubmitting.</p></div>@endif
<form class="mt-6 max-w-4xl space-y-6" method="POST" enctype="multipart/form-data" action="{{ isset($order) ? ($order->status === \App\Enums\WorkOrderStatus::NeedsInformation ? route('work-orders.workflow', [$order, 'resubmit']) : route('work-orders.update', $order)) : route('work-orders.store') }}">@csrf @if(isset($order) && $order->status === \App\Enums\WorkOrderStatus::Submitted) @method('PUT') @endif
<section class="form-section"><h2>1. Work Type</h2><p>Select the type and urgency of the requested facilities work.</p><div class="grid gap-5 sm:grid-cols-2"><label>Work type <span class="text-rose-600">*</span><select name="work_order_category_id" required>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('work_order_category_id', $order->work_order_category_id ?? null) == $category->id)>{{ $category->name }}</option>@endforeach</select></label><label>Requester urgency <span class="text-rose-600">*</span><select name="urgency"><option value="NORMAL" @selected(old('urgency', $order->urgency ?? 'NORMAL') === 'NORMAL')>Normal</option><option value="URGENT" @selected(old('urgency', $order->urgency ?? 'NORMAL') === 'URGENT')>Urgent</option></select></label></div></section>
<section class="form-section"><h2>2. Location</h2><p>Choose the campus and the most specific available location.</p><div class="grid gap-5 sm:grid-cols-2"><label>Campus <span class="text-rose-600">*</span><select name="campus_id" id="campus" required>@foreach($campuses as $campus)<option value="{{ $campus->id }}" @selected(old('campus_id', $order->campus_id ?? null) == $campus->id)>{{ $campus->name }}</option>@endforeach</select></label><label>Building <span class="text-rose-600">*</span><select name="building_id" id="building" required>@foreach($buildings as $building)<option data-campus="{{ $building->campus_id }}" value="{{ $building->id }}" @selected(old('building_id', $order->building_id ?? null) == $building->id)>{{ $building->name }}</option>@endforeach</select></label><label>Floor <span class="text-slate-400">(optional)</span><select name="floor_id" id="floor"><option value="">Not specified</option>@foreach($floors as $floor)<option data-building="{{ $floor->building_id }}" value="{{ $floor->id }}" @selected(old('floor_id', $order->floor_id ?? null) == $floor->id)>{{ $floor->name }}</option>@endforeach</select></label><label>Office / room / area <span class="text-slate-400">(optional)</span><select name="building_location_id" id="location"><option value="">Not specified</option>@foreach($locations as $location)<option data-building="{{ $location->building_id }}" data-floor="{{ $location->floor_id }}" value="{{ $location->id }}" @selected(old('building_location_id', $order->building_location_id ?? null) == $location->id)>{{ $location->name }}</option>@endforeach</select></label></div></section>
<section class="form-section"><h2>3. Request Details</h2><p>Describe the issue clearly so FMO can prepare and respond appropriately.</p><div class="space-y-5"><label>Subject <span class="text-rose-600">*</span><input name="subject" value="{{ old('subject', $order->subject ?? '') }}" required maxlength="255" placeholder="Example: Electrical outlet is not working"></label><label>What work is needed? <span class="text-rose-600">*</span><textarea name="description" required placeholder="Describe the issue, its impact, and any helpful details.">{{ old('description', $order->description ?? '') }}</textarea></label></div></section>
<section class="form-section"><h2>4. Personnel Preference</h2><p>A preference is considered when practical, but it is not an assignment.</p><label>Preferred FMO personnel <select name="preferred_fmo_personnel_id"><option value="">No preference</option>@foreach($personnel as $person)<option value="{{ $person->id }}" @selected(old('preferred_fmo_personnel_id', $order->preferred_fmo_personnel_id ?? null) == $person->id)>{{ $person->user->name }} — {{ $person->designation }}</option>@endforeach</select></label></section>
<section class="form-section"><h2>5. Attachments</h2><p>Add helpful photos or short video evidence. Accepted: JPEG, PNG, WebP, MP4; up to {{ config('work_orders.attachments.max_count') }} files.</p><label class="block rounded-lg border border-dashed border-slate-300 bg-slate-50 p-5 text-center">Choose files<input class="mt-3" type="file" name="attachments[]" multiple accept="image/jpeg,image/png,image/webp,video/mp4"></label></section>
@if(isset($order) && $order->status === \App\Enums\WorkOrderStatus::NeedsInformation)<section class="form-section"><h2>6. Response to FMO</h2><label>Additional information <span class="text-rose-600">*</span><textarea name="requester_message" required></textarea></label></section>@endif
<div class="flex flex-wrap gap-3"><button class="btn btn-primary" type="submit">{{ isset($order) ? 'Save and resubmit' : 'Submit Work Order' }}</button>@if(!isset($order)) @can('work_orders.create_direct')<button class="btn btn-success" type="submit" formaction="{{ route('work-orders.direct') }}">Create direct authorized Work Order</button>@endcan @endif<a class="btn btn-secondary" href="{{ route('work-orders.mine') }}">Cancel</a></div></form>
<script>const campus=document.querySelector('#campus'),building=document.querySelector('#building'),floor=document.querySelector('#floor'),location=document.querySelector('#location');function filter(select,key,value){[...select.options].forEach(option=>option.hidden=!!option.dataset[key]&&option.dataset[key]!==value);if(select.selectedOptions[0]?.hidden)select.value='';}function sync(){filter(building,'campus',campus.value);filter(floor,'building',building.value);filter(location,'building',building.value);if(floor.value)filter(location,'floor',floor.value);}campus.onchange=sync;building.onchange=sync;floor.onchange=sync;sync();</script>
@endsection
