@extends('layouts.app')
@section('title', isset($order) ? 'Update Work Order' : 'New Work Order Request')
@section('content')
<h1 class="text-2xl font-semibold">{{ isset($order) ? 'Update Work Order '.$order->work_order_number : 'New Work Order Request' }}</h1>
@if(isset($order) && $order->status === \App\Enums\WorkOrderStatus::NeedsInformation)
<p class="mt-3 rounded bg-amber-100 p-3">FMO requested additional information. Update the request and resubmit it for screening.</p>
@endif
<form class="mt-5 max-w-3xl space-y-3 rounded border bg-white p-6" method="POST" enctype="multipart/form-data" action="{{ isset($order) ? ($order->status === \App\Enums\WorkOrderStatus::NeedsInformation ? route('work-orders.workflow', [$order, 'resubmit']) : route('work-orders.update', $order)) : route('work-orders.store') }}">
@csrf
@if(isset($order) && $order->status === \App\Enums\WorkOrderStatus::Submitted) @method('PUT') @endif
<label class="block">Work category<select class="mt-1 w-full rounded border p-2" name="work_order_category_id">@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('work_order_category_id', $order->work_order_category_id ?? null) == $category->id)>{{ $category->name }}</option>@endforeach</select></label>
<label class="block">Campus<select class="mt-1 w-full rounded border p-2" name="campus_id" id="campus">@foreach($campuses as $campus)<option value="{{ $campus->id }}" @selected(old('campus_id', $order->campus_id ?? null) == $campus->id)>{{ $campus->name }}</option>@endforeach</select></label>
<label class="block">Building<select class="mt-1 w-full rounded border p-2" name="building_id" id="building">@foreach($buildings as $building)<option data-campus="{{ $building->campus_id }}" value="{{ $building->id }}" @selected(old('building_id', $order->building_id ?? null) == $building->id)>{{ $building->name }}</option>@endforeach</select></label>
<label class="block">Floor, optional<select class="mt-1 w-full rounded border p-2" name="floor_id" id="floor"><option value="">None</option>@foreach($floors as $floor)<option data-building="{{ $floor->building_id }}" value="{{ $floor->id }}" @selected(old('floor_id', $order->floor_id ?? null) == $floor->id)>{{ $floor->name }}</option>@endforeach</select></label>
<label class="block">Office / Room / Area, optional<select class="mt-1 w-full rounded border p-2" name="building_location_id" id="location"><option value="">None</option>@foreach($locations as $location)<option data-building="{{ $location->building_id }}" data-floor="{{ $location->floor_id }}" value="{{ $location->id }}" @selected(old('building_location_id', $order->building_location_id ?? null) == $location->id)>{{ $location->name }}</option>@endforeach</select></label>
<label class="block">Subject<input class="mt-1 w-full rounded border p-2" name="subject" value="{{ old('subject', $order->subject ?? '') }}" required></label>
<label class="block">Work needed<textarea class="mt-1 w-full rounded border p-2" name="description" required>{{ old('description', $order->description ?? '') }}</textarea></label>
<label class="block">Requester urgency<select class="mt-1 w-full rounded border p-2" name="urgency"><option value="NORMAL" @selected(old('urgency', $order->urgency ?? 'NORMAL') === 'NORMAL')>Normal</option><option value="URGENT" @selected(old('urgency', $order->urgency ?? 'NORMAL') === 'URGENT')>Urgent</option></select></label>
<label class="block">Preferred FMO personnel, optional<select class="mt-1 w-full rounded border p-2" name="preferred_fmo_personnel_id"><option value="">No preference</option>@foreach($personnel as $person)<option value="{{ $person->id }}" @selected(old('preferred_fmo_personnel_id', $order->preferred_fmo_personnel_id ?? null) == $person->id)>{{ $person->user->name }} — {{ $person->designation }}</option>@endforeach</select><span class="text-sm text-slate-500">A preference is not an assignment.</span></label>
<label class="block">Photos or short MP4 videos, up to {{ config('work_orders.attachments.max_count') }}<input class="mt-1 w-full" type="file" name="attachments[]" multiple accept="image/jpeg,image/png,image/webp,video/mp4"></label>
@if(isset($order) && $order->status === \App\Enums\WorkOrderStatus::NeedsInformation)<label class="block">Response to FMO<textarea class="mt-1 w-full rounded border p-2" name="requester_message" required></textarea></label>@endif
<div class="flex gap-3"><button class="rounded bg-blue-700 px-4 py-2 text-white">{{ isset($order) ? 'Save and resubmit' : 'Submit request' }}</button>@if(!isset($order)) @can('work_orders.create_direct')<button class="rounded bg-emerald-700 px-4 py-2 text-white" formaction="{{ route('work-orders.direct') }}">Create direct authorized Work Order</button>@endcan @endif</div>
</form>
<script>const campus=document.querySelector('#campus'),building=document.querySelector('#building'),floor=document.querySelector('#floor'),location=document.querySelector('#location');function filter(select,key,value){[...select.options].forEach(option=>option.hidden=!!option.dataset[key]&&option.dataset[key]!==value);if(select.selectedOptions[0]?.hidden)select.value='';}function sync(){filter(building,'campus',campus.value);filter(floor,'building',building.value);filter(location,'building',building.value);if(floor.value)filter(location,'floor',floor.value);}campus.onchange=sync;building.onchange=sync;floor.onchange=sync;sync();</script>
@endsection
