@extends('layouts.app')
@section('title', 'Dashboard')
@section('content')
<x-page-header :title="$management ? 'Work Order Overview' : 'My Work Orders'" :description="$management ? 'A focused view of operational queues and work requiring attention.' : 'Track your requests and the facilities work assigned to you.'">
    <x-slot:action><a class="btn btn-secondary" href="{{ route('reports.history') }}">View work history</a></x-slot:action>
</x-page-header>
<form method="GET" action="{{ route('dashboard') }}" class="filter-bar mt-6"><label>From<input type="date" name="from" value="{{ $from }}"></label><label>Through<input type="date" name="to" value="{{ $to }}"></label><button class="btn btn-primary" type="submit">Apply period</button></form>
<section class="mt-8"><div class="flex items-baseline justify-between"><div><h2 class="text-lg">Current Work Orders</h2><p class="mt-1 text-sm text-slate-500">Select a status to view the corresponding history.</p></div></div>
<div class="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
@foreach (['SUBMITTED'=>'New requests','FOR_SCREENING'=>'For screening','FOR_APPROVAL'=>'For approval','APPROVED'=>'Awaiting assignment','ASSESSMENT_REVIEW'=>'Assessment review','IN_PROGRESS'=>'In progress','FOR_VERIFICATION'=>'For verification','COMPLETED'=>'Completed this month'] as $status => $label)
    <x-stat-card :label="$label" :value="$counts[$status] ?? 0" :href="route('reports.history', ['status' => $status])" />
@endforeach
</div></section>
<section class="mt-8"><h2 class="text-lg">Selected period</h2><div class="mt-4 grid gap-4 sm:grid-cols-3"><x-stat-card label="Submitted" :value="$periodSubmitted" /><x-stat-card label="Verified complete" :value="$periodCompleted" /><x-stat-card label="Average time to completion" :value="$averageHours === null ? '—' : number_format($averageHours, 1).' hours'" /></div></section>
@if ($management)
<div class="mt-8 grid gap-6 xl:grid-cols-2"><section class="section-card"><h2 class="text-lg">Needs Attention</h2><p class="mt-1 text-sm text-slate-500">Age indicators help prioritize review; they are not SLA violations.</p><div class="mt-5 space-y-3">@forelse($attention as $order) @php($hours = \Carbon\Carbon::parse($order->state_entered_at ?? $order->updated_at, 'Asia/Manila')->diffInHours(now())) @php($threshold = config('reporting.attention_hours.'.$order->status->value))
    <a href="{{ route('work-orders.show', $order) }}" class="block rounded-lg border border-slate-200 p-4 transition hover:border-blue-300 hover:bg-blue-50/30"><div class="flex flex-wrap items-center justify-between gap-2"><span class="font-semibold text-blue-800">{{ $order->work_order_number }}</span><x-status-badge :status="$order->status" /></div><p class="mt-1 font-medium text-slate-800">{{ $order->subject }}</p><p class="mt-1 text-sm text-slate-500">{{ $order->building->name }} · {{ number_format($hours, 0) }} hours in current state @if($threshold && $hours >= $threshold) · Review recommended @endif</p></a>
@empty <x-empty-state title="Nothing currently needs attention" description="Operational items needing review will appear here." /> @endforelse</div></section>
<section class="section-card"><h2 class="text-lg">Active Staff Sessions</h2><p class="mt-1 text-sm text-slate-500">Current on-site work, visible to authorized management.</p><div class="mt-5 space-y-3">@forelse($activeSessions as $session)<a href="{{ route('work-orders.show', $session->workOrder) }}" class="block rounded-lg border border-slate-200 p-4 transition hover:border-blue-300"><p class="font-semibold text-slate-800">{{ $session->personnel->user->name }} <span class="font-normal text-slate-500">· {{ $session->workOrder->work_order_number }}</span></p><p class="mt-1 text-sm text-slate-500">{{ $session->workOrder->building->name }} · Active {{ number_format($session->started_at->diffInHours(now()), 0) }} hours</p></a>@empty <x-empty-state title="No active work sessions" description="Active staff sessions will be displayed here." /> @endforelse</div></section></div>
<section class="mt-8 section-card"><h2 class="text-lg">Personnel Open Workload</h2><p class="mt-1 text-sm text-slate-500">Current assignment counts, not performance ratings.</p><div class="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">@forelse($personnelWorkload as $person)<div class="rounded-lg border border-slate-200 px-4 py-3"><p class="font-medium text-slate-800">{{ $person->user->name }}</p><p class="mt-1 text-sm text-slate-500">{{ $person->open_workload }} open Work Orders</p></div>@empty <p class="text-sm text-slate-500">No active personnel profiles.</p>@endforelse</div></section>
@endif
@endsection
