<?php

return [
    'permissions' => [
        'users.view_pending_registrations',
        'users.approve_registration',
        'users.reject_registration',
        'users.request_registration_correction',
        'users.view',
        'users.manage_status',
        'users.assign_roles',
        'users.assign_permissions',
        'roles.view',
        'roles.create',
        'roles.update',
        'roles.delete',
        'permissions.view',
        'permissions.manage',
        'personnel.view',
        'personnel.create',
        'personnel.update',
        'personnel.manage_status',
        'personnel.delete',
        'skills.view',
        'skills.create',
        'skills.update',
        'skills.delete',
        'profiles.view_own',
        'profiles.update_own',
        'profiles.view_others',
        'profiles.update_others',
        'campuses.view', 'campuses.create', 'campuses.update', 'campuses.manage_status', 'campuses.delete',
        'buildings.view', 'buildings.create', 'buildings.update', 'buildings.manage_status', 'buildings.delete',
        'locations.view', 'locations.create', 'locations.update', 'locations.manage_status', 'locations.delete',
        'work_orders.create', 'work_orders.view_own', 'work_orders.view_all', 'work_orders.update_own_submitted',
        'work_orders.screen', 'work_orders.request_information', 'work_orders.recommend', 'work_orders.approve', 'work_orders.disapprove', 'work_orders.return_to_screening', 'work_orders.resubmit_own', 'work_orders.create_direct',
        'work_orders.assign', 'work_orders.reassign', 'work_orders.remove_assignee', 'work_orders.assign_direct', 'work_orders.view_assigned',
        'work_orders.assess_assigned', 'work_orders.view_assessments', 'work_orders.resolve_assessment', 'work_orders.cancel', 'work_orders.mark_beyond_scope', 'work_orders.refer_external',
        'work_orders.start_assigned', 'work_orders.update_assigned', 'work_orders.end_session', 'work_orders.submit_completion', 'work_orders.view_execution', 'work_orders.verify_completion', 'work_orders.return_for_work', 'work_orders.manage_sessions',
        'work_order_categories.view', 'work_order_categories.create', 'work_order_categories.update', 'work_order_categories.manage_status', 'work_order_categories.delete',
        'dashboard.view_management', 'dashboard.view_oversight',
        'reports.view_work_orders', 'reports.export_work_orders', 'reports.view_personnel_history', 'reports.view_location_history',
    ],
    'delegable_permissions' => [
        'users.view_pending_registrations',
        'users.approve_registration',
        'users.reject_registration',
        'users.request_registration_correction',
        'personnel.view',
        'personnel.create',
        'personnel.update',
        'personnel.manage_status',
        'skills.view',
        'skills.create',
        'skills.update',
        'buildings.view', 'buildings.create', 'buildings.update', 'buildings.manage_status',
        'locations.view', 'locations.create', 'locations.update', 'locations.manage_status',
        'work_order_categories.create', 'work_order_categories.update', 'work_order_categories.manage_status',
        'work_orders.screen', 'work_orders.request_information', 'work_orders.recommend', 'work_orders.approve', 'work_orders.disapprove', 'work_orders.return_to_screening',
        'work_orders.assign', 'work_orders.reassign', 'work_orders.remove_assignee',
        'work_orders.resolve_assessment', 'work_orders.cancel', 'work_orders.mark_beyond_scope', 'work_orders.refer_external',
        'work_orders.view_execution', 'work_orders.verify_completion', 'work_orders.return_for_work', 'work_orders.manage_sessions',
    ],
    'core_roles' => [
        'Requester', 'FMO Staff', 'FMO Dispatcher', 'FMO Head',
        'Campus Director', 'Director for Instruction', 'FMO Oversight',
        'System Administrator',
    ],
];
