<?php

return [
    'permissions' => [
        'users.view_pending_registrations',
        'users.approve_registration',
        'users.reject_registration',
        'users.request_registration_correction',
        'users.view',
        'users.manage_status',
        'users.assign_roles',
        'users.assign_permissions',
        'roles.view',
        'roles.create',
        'roles.update',
        'roles.delete',
        'permissions.view',
        'permissions.manage',
        'personnel.view',
        'personnel.create',
        'personnel.update',
        'personnel.manage_status',
        'personnel.delete',
        'skills.view',
        'skills.create',
        'skills.update',
        'skills.delete',
        'profiles.view_own',
        'profiles.update_own',
        'profiles.view_others',
        'profiles.update_others',
        'campuses.view', 'campuses.create', 'campuses.update', 'campuses.manage_status', 'campuses.delete',
        'buildings.view', 'buildings.create', 'buildings.update', 'buildings.manage_status', 'buildings.delete',
        'locations.view', 'locations.create', 'locations.update', 'locations.manage_status', 'locations.delete',
        'work_orders.create', 'work_orders.view_own', 'work_orders.view_all', 'work_orders.update_own_submitted',
        'work_order_categories.view', 'work_order_categories.create', 'work_order_categories.update', 'work_order_categories.manage_status', 'work_order_categories.delete',
    ],
    'delegable_permissions' => [
        'users.view_pending_registrations',
        'users.approve_registration',
        'users.reject_registration',
        'users.request_registration_correction',
        'personnel.view',
        'personnel.create',
        'personnel.update',
        'personnel.manage_status',
        'skills.view',
        'skills.create',
        'skills.update',
        'buildings.view', 'buildings.create', 'buildings.update', 'buildings.manage_status',
        'locations.view', 'locations.create', 'locations.update', 'locations.manage_status',
        'work_order_categories.create', 'work_order_categories.update', 'work_order_categories.manage_status',
    ],
    'core_roles' => [
        'Requester', 'FMO Staff', 'FMO Dispatcher', 'FMO Head',
        'Campus Director', 'Director for Instruction', 'FMO Oversight',
        'System Administrator',
    ],
];
